### PR TITLE
Enable JSON schema validation for JSON entity fields

### PR DESCRIPTION
**Pull request by dnlkoch**
This enables validation for the JSON fields of the SHOGun entities based on the OpenAPI specification. 

Screenshot from 2021-09-23 17-51-28

Please review @terrestris/devs.

### CODE REVIEW

**Review by ahennr — APPROVED** [review]
🔝

**Review by hwbllmnn — APPROVED** [review]

**Review by annarieger — APPROVED** [review]
Very cool! 👍🏻

**Review by KaiVolland — APPROVED** [review]
:fire:

**Comment by dnlkoch** [comment]
Thanks for the reviews!

**Pull request merged**
